language: python

python:
  - "3.5"

env:
  global:
    - SAMTOOLS_INSTALL=~/samtools-install
    - PATH=$PATH:$SAMTOOLS_INSTALL/bin

before_install:
  - pip install codecov    

install:
  - ./scripts/install-samtools.sh $SAMTOOLS_INSTALL
  - pip install -r requirements.txt

script:
  - nosetests -v --with-coverage --cover-package=checks --cover-inclusive

after_success:
  - codecov
